#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : notebook
Version  : 5.3.1
Release  : 16
URL      : https://pypi.python.org/packages/1f/f1/2df6d4240d82b24cbba6228474d06537da5acfd2934036e2a258192179e5/notebook-5.3.1.tar.gz
Source0  : https://pypi.python.org/packages/1f/f1/2df6d4240d82b24cbba6228474d06537da5acfd2934036e2a258192179e5/notebook-5.3.1.tar.gz
Summary  : A web-based notebook environment for interactive computing
Group    : Development/Tools
License  : BSD-3-Clause-Clear
Requires: notebook-bin
Requires: notebook-python3
Requires: notebook-python
Requires: Jinja2
Requires: ipykernel
Requires: ipython_genutils
Requires: jupyter_client
Requires: jupyter_core
Requires: nbconvert
Requires: nbformat
Requires: terminado
Requires: tornado
Requires: traitlets
BuildRequires : Jinja2
BuildRequires : ipykernel
BuildRequires : ipython_genutils
BuildRequires : jupyter_client
BuildRequires : jupyter_core
BuildRequires : nbconvert
BuildRequires : nbformat
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : terminado
BuildRequires : tornado
BuildRequires : traitlets

%description
The Jupyter Notebook is a web application that allows you to create and
        share documents that contain live code, equations, visualizations, and
        explanatory text. The Notebook has support for multiple programming
        languages, sharing, and interactive widgets.

%package bin
Summary: bin components for the notebook package.
Group: Binaries

%description bin
bin components for the notebook package.


%package python
Summary: python components for the notebook package.
Group: Default
Requires: notebook-python3

%description python
python components for the notebook package.


%package python3
Summary: python3 components for the notebook package.
Group: Default
Requires: python3-core

%description python3
python3 components for the notebook package.


%prep
%setup -q -n notebook-5.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1516136060
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/jupyter-bundlerextension
/usr/bin/jupyter-nbextension
/usr/bin/jupyter-notebook
/usr/bin/jupyter-serverextension

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
